// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbekddjiflstedhvrhwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZWtkZGppZmxzdGVkaHZyaHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjI4MzIsImV4cCI6MjA2NzAzODgzMn0.Wp_tj9gfoaSaIbRUjknUD4FF6ILoe9P-psGlqoX7fhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});